<a href="https://colab.research.google.com/github/EricCostaDev/sqlite-python/blob/main/sqlite_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import os

if os.path.isfile('pizzaria.db'):
    tabela_ja_criada_anteriormente = True
    print('O banco de dados já existe')
else:
    print('O banco de dados não existe')
    tabela_ja_criada_anteriormente = False

# conectando ao banco de dados
conn = sqlite3.connect('pizzaria.db')


if tabela_ja_criada_anteriormente:
  # cria as tabelas se elas não existirem
  cursor = conn.cursor()

  cursor.execute("""
        CREATE TABLE IF NOT EXISTS clientes (
          id_cliente INTEGER PRIMARY KEY,
          nome VARCHAR(50),
          telefone VARCHAR(20),
          email VARCHAR(50),
          CPF VARCHAR(11)
        );
  """)

  cursor.execute("""
        CREATE TABLE IF NOT EXISTS pizzas (
          id_pizza INTEGER PRIMARY KEY,
          id_configuracao INTEGER,
          FOREIGN KEY (id_configuracao) REFERENCES pizzas_configuracao(id_configuracao)
        );
  """)

  cursor.execute("""
        CREATE TABLE IF NOT EXISTS pizzas_sabores (
          id_pizza_sabor INTEGER PRIMARY KEY,
          id_pizza INTEGER,
          id_sabor INTEGER,
          FOREIGN KEY (id_pizza) REFERENCES pizzas(id_pizza),
          FOREIGN KEY (id_sabor) REFERENCES sabores(id_sabor)
        );
  """)

  cursor.execute("""
        CREATE TABLE IF NOT EXISTS sabores (
          id_sabor INTEGER PRIMARY KEY,
          nome VARCHAR(50),
          tipo VARCHAR(50),
          descricao VARCHAR(100),
          valor_adicional decimal (5,2)
        );
  """)



  cursor.execute("""
        CREATE TABLE IF NOT EXISTS enderecos (
          id_endereco INTEGER PRIMARY KEY,
          logradouro VARCHAR(100), 
          numero VARCHAR(100), 
          bairro VARCHAR(100),
          cidade VARCHAR(50),
          estado VARCHAR(50),
          CEP VARCHAR(8),
          complemento varchar (50),
          apelido varchar (50)
        );
  """)


  cursor.execute("""
      CREATE TABLE IF NOT EXISTS entregadores (
          id_entregador INTEGER PRIMARY KEY,
          nome VARCHAR(50),
          telefone VARCHAR(20),
          veiculo VARCHAR(30)
      );
  """)

  cursor.execute("""
      CREATE TABLE IF NOT EXISTS bordas (
          id_borda INTEGER PRIMARY KEY,
          nome VARCHAR(50),
          descricao VARCHAR(100),
          valor_adicional DECIMAL(5,2)
      );
  """)

  cursor.execute("""
      CREATE TABLE IF NOT EXISTS pedidos (
          id_pedido INTEGER PRIMARY KEY,
          id_cliente INTEGER,
          id_endereco INTEGER,
          id_entregador INTEGER,
          data DATETIME,
          preco_pedido DECIMAL(5,2),
          valor_entrega DECIMAL(5,2),
          preco_total DECIMAL(5,2),
          FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
          FOREIGN KEY (id_endereco) REFERENCES enderecos(id_endereco),
          FOREIGN KEY (id_entregador) REFERENCES entregadores(id_entregador)
      );
  """)

  cursor.execute("""
      CREATE TABLE IF NOT EXISTS itens_pedido (
          id_item_pedido INTEGER PRIMARY KEY,
          id_pedido INTEGER,
          id_pizza INTEGER,
          id_bebida INTEGER,
          quantidade INTEGER,
          preco DECIMAL(5,2),
          FOREIGN KEY (id_pedido) REFERENCES pedidos(id_pedido),
          FOREIGN KEY (id_pizza) REFERENCES pizzas(id_pizza),
          FOREIGN KEY (id_bebida) REFERENCES bebidas(id_bebida)
      );
  """)

  cursor.execute("""
      CREATE TABLE IF NOT EXISTS historico (
          id_historico INTEGER PRIMARY KEY,
          id_pedido INTEGER,
          forma_pagamento varchar (50),
          data DATETIME,
          FOREIGN KEY (id_pedido) REFERENCES pedidos(id_pedido)
      );
  """)

  cursor.execute("""
        CREATE TABLE IF NOT EXISTS bebidas (
          id_bebida INTEGER PRIMARY KEY,
          nome VARCHAR(50),
          descricao VARCHAR(100),
          preco DECIMAL(5,2)
        );
  """)

  cursor.execute("""
      CREATE TABLE IF NOT EXISTS clientes_enderecos (
        id_cliente_endereco INTEGER PRIMARY KEY,
        id_cliente INTEGER,
        id_endereco INTEGER,
        principal BOOLEAN,
        FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente),
        FOREIGN KEY (id_endereco) REFERENCES enderecos(id_endereco)
      );
  """)

  cursor.execute("""
      CREATE TABLE IF NOT EXISTS tamanho (
        id_tamanho INTEGER PRIMARY KEY,
        nome VARCHAR,
        descricao VARCHAR,
        valor_base DECIMAL(5,2),
        maximo_sabores INTEGER
      );
  """)

  # cursor.execute("""
  #       CREATE TABLE IF NOT EXISTS tipo_sabor (
  #         id_tipo_sabor INTEGER PRIMARY KEY,
  #         nome VARCHAR,
  #         descricao VARCHAR,
  #         valor_adicional DECIMAL(5,2)
  #       );
  # """)

  cursor.execute("""
        CREATE TABLE IF NOT EXISTS pizzas_configuracao (
          id_configuracao INTEGER PRIMARY KEY,
          id_tamanho INTEGER,
          id_sabor INTEGER,
          id_borda INTEGER,
          valor_adicional_total DECIMAL(5,2),
          FOREIGN KEY (id_tamanho) REFERENCES tamanho(id_tamanho),
          FOREIGN KEY (id_sabor) REFERENCES sabores(id_sabor),
          FOREIGN KEY (id_borda) REFERENCES bordas(id_borda)
        );

  """)



  if tabela_ja_criada_anteriormente == False:

      cursor.execute("INSERT INTO clientes (nome, telefone, email, CPF) VALUES (?, ?, ?, ?)", ('João Silva', '(41) 98765-4321', 'joao.silva@gmail.com', '123.456.789-00'))
      cursor.execute("INSERT INTO clientes (nome, telefone, email, CPF) VALUES (?, ?, ?, ?)", ('Maria Souza', '(41) 99876-5432', 'maria.souza@hotmail.com', '987.654.321-00'))



      # insere alguns tamanhos de pizza
      cursor.execute("INSERT INTO tamanho (nome, descricao, valor_base, maximo_sabores) VALUES (?, ?, ?, ?)", ('Broto', '6 fatias', 29.99, 2))
      cursor.execute("INSERT INTO tamanho (nome, descricao, valor_base, maximo_sabores) VALUES (?, ?, ?, ?)", ('Médio', '8 fatias', 29.99, 2))
      cursor.execute("INSERT INTO tamanho (nome, descricao, valor_base, maximo_sabores) VALUES (?, ?, ?, ?)", ('Grande', '12 fatias', 39.99, 3))


      # insere alguns sabores de pizza
      cursor.execute("INSERT INTO sabores (nome, tipo) VALUES (?, ?)", ('Mussarela', 'tradicional'))
      cursor.execute("INSERT INTO sabores (nome, tipo) VALUES (?, ?)", ('Frango com Catupiry', 'especial'))


      # insere algumas bebidas
      bebidas_data = [
          ('Guaraná Antartica', 4.99, 350),
          ('Fanta Laranja', 4.99, 350),
          ('Suco de Laranja', 7.99, 500),
          ('Água Mineral', 2.99, 500)
      ]
      cursor.executemany("INSERT INTO bebidas (nome, preco, quantidade_ml) VALUES (?, ?, ?)", bebidas_data)


      cursor.execute("INSERT INTO entregadores (nome, telefone) VALUES (?, ?)", ('João Silva', '11999999999'))


      cursor.execute("INSERT INTO enderecos (lograd, numero, complemento, bairro, cidade, estado, cep) VALUES (?, ?, ?, ?, ?, ?, ?)", ('Rua A', '123', 'Apto 1', 'Centro', 'Curitiba', 'PR', '01001-000'))


      bordas = [('Cheddar', 6.99), ('Requeijão', 4.99), ('Calabresa', 7.99)]
      cursor.executemany("INSERT INTO bordas (nome, preco) VALUES (?, ?)", bordas)

      cursor.execute("INSERT INTO pedidos (id_cliente, id_endereco, id_entregador, forma_pagamento, valor_total, data_pedido) VALUES (?, ?, ?, ?, ?, ?)",
                (1, 1, 1, 'Dinheiro', 35.0, '2023-02-09 15:30:00'))


      # cursor.execute("INSERT INTO tipo_sabor (nome, descricao, valor_adicional) VALUES (?, ?, ?)", ('Tradicional', 'Sabor clássico da pizza', 0.0))

      # cursor.execute("INSERT INTO tipo_sabor (nome, descricao, valor_adicional) VALUES (?, ?, ?)", ('Especial', 'Sabor gourmet com ingredientes exclusivos', 5.0))

      cursor.execute("INSERT INTO clientes_enderecos (id_cliente, logradouro, numero, complemento, bairro, cidade, estado, cep) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (1, 'Rua A', '123', 'Apto 101', 'Centro', 'Curitiba', 'PR', '01000-000'))


      cursor.execute("INSERT INTO clientes_enderecos (id_cliente, logradouro, numero, complemento, bairro, cidade, estado, cep) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (2, 'Rua B', '456', 'Casa 2', 'Jardim', 'Curitiba', 'PR', '02000-000'))
      
      cursor.execute("INSERT INTO pizzas (id_pizza, id_configuracao) VALUES (?, ?)",
                (1, 1))
      
      cursor.execute("INSERT INTO pizzas_sabores (id_pizza, id_sabor) VALUES (?, ?)",
                (1, 1))
      
      cursor.execute("INSERT INTO pizzas_sabores (id_pizza, id_sabor) VALUES (?, ?)",
                (1, 1))
      
      cursor.execute("INSERT INTO itens_pedido (id_pedido, id_pizza, id_bebida, id_borda) VALUES (?, ?, ?, ?)",
                (1, 1, 2, 1))
      
      cursor.execute("INSERT INTO historico (id_historico, id_pedido, forma_pagamento, data) VALUES (?, ?, ?, ?)",
                (1, 1, 'Dinheiro', '2023-02-09 13:30:00'))
      
      cursor.execute("INSERT INTO pizzas_configuracao (id_configuracao, id_tamanho, id_tipo_sabor, id_borda) VALUES (?, ?, ?, ?)",
                (1, 1, 1, 1))

O banco de dados não existe

In [ ]:
def inserir_cliente(nome, telefone, enderecos):
    conn = sqlite3.connect('pizzaria.db', timeout=10)
    cursor = conn.cursor()

    # Inserindo novo cliente
    cursor.execute("INSERT INTO clientes  (nome, telefone,email) VALUES (?, ?)", (nome, telefone))
    id_cliente = cursor.lastrowid

    # Inserindo endereços do cliente na tabela clientes_enderecos
    for endereco in enderecos:
        cursor.execute("INSERT INTO enderecos (logradouro, numero, complemento, bairro, cidade, estado, cep) VALUES (?, ?, ?, ?, ?, ?, ?)",
                       endereco)
        id_endereco = cursor.lastrowid
        cursor.execute("INSERT INTO clientes_enderecos (id_cliente, id_endereco) VALUES (?, ?)", (id_cliente, id_endereco))

    conn.commit()
    conn.close()

In [ ]:
enderecos = [ 'logradouro', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'cep']
inserir_cliente('nome', 'telefone', enderecos)

In [ ]:
def fazer_pedido(cpf_cliente):
    # Conectar ao banco de dados
    conn = sqlite3.connect('pizzaria.db')
    cursor = conn.cursor()

    # Buscar informações do cliente
    cursor.execute("SELECT id_cliente FROM clientes WHERE cpf=?", (cpf_cliente,))
    result = cursor.fetchone()
    if result is None:
        print("Cliente não encontrado.")
        return

    id_cliente = result[0]

    # Buscar endereços do cliente
    cursor.execute("SELECT id_endereco, logradouro, numero, complemento, bairro, cidade, estado, cep FROM clientes_enderecos WHERE id_cliente=?", (id_cliente,))
    enderecos = cursor.fetchall()

    if len(enderecos) == 0:
        print("Cliente não possui endereços cadastrados.")
        return

    # Mostrar opções de endereços para entrega
    print("Selecione o endereço de entrega:")
    for endereco in enderecos:
        print("Código: {}".format(endereco[0]))
        print("Logradouro: {}".format(endereco[1]))
        print("Número: {}".format(endereco[2]))
        print("Complemento: {}".format(endereco[3]))
        print("Bairro: {}".format(endereco[4]))
        print("Cidade: {}".format(endereco[5]))
        print("Estado: {}".format(endereco[6]))
        print("CEP: {}".format(endereco[7]))
        print()

    # Realizar o pedido
    endereco_entrega = int(input("Digite o código do endereço de entrega: "))
    forma_pagamento = input("Digite a forma de pagamento (Dinheiro, Credito, Debito, Pix): ")
    items_pedido = []

    while True:
            # Selecionar tamanho da pizza
        cursor.execute("SELECT id_tamanho, nome, maximo_sabores, FROM tamanho")
        tamanhos = cursor.fetchall()

        print("Selecione o tamanho da pizza:")
        for tamanho in tamanhos:
            print("Código: {}".format(tamanho[0]))
            print("Nome: {}".format(tamanho[1]))
            print("Max de sabores: {}".format(tamanho[2]))
            print()

        codigo_tamanho = int(input("Digite o código do tamanho da pizza: "))

        cursor.execute("SELECT id_tamanho,maximo_sabores,valor_base FROM tamanho WHERE id_tamanho = ? ",(codigo_tamanho))
        
        maximo_sabores = cursor.fetchall()[1]
        valor_base = cursor.fetchall()[2]
        
        # Selecionar sabor da pizza
        cursor.execute("SELECT * FROM sabores")
        sabores = cursor.fetchall()
        codigos_sabores = []
        valor_adicional_sabor = 0

        for i in range(0,maximo_sabores - 1):
          print("Selecione um sabor:")
          for sabor in sabores:
            print("Código: {}".format(sabor[0]))
            print("Nome: {}".format(sabor[1]))
            print()
          codigo_sabor = int(input("Digite o código do sabor da pizza: "))
          cursor.execute("SELECT id_sabor,valor_adicional FROM sabores WHERE id_sabor = ? ",(codigo_sabor))
          
          if(cursor.fetchall()[1] >= valor_adicional):
            valor_adicional_sabor = cursor.fetchall()[1]
          
          codigos_sabores.append(codigo_sabor)


        
        # Selecionar borda da pizza
        cursor.execute("SELECT id_borda, nome, valor_adicional FROM bordas")
        bordas = cursor.fetchall()

        print("Selecione a borda da pizza:")
        for borda in bordas:
            print("Código: {}".format(borda[0]))
            print("Nome: {}".format(borda[1]))
            print("Preço: {}".format(borda[2]))
            print()

        codigo_borda = int(input("Digite o código da borda da pizza: "))
        cursor.execute("SELECT id_borda, nome, valor_adicional FROM bordas WHERE id_borda = ? ",(codigo_borda))

        valor_borda = cursor.fetchall()[2]

        # Selecionar quantidade da pizza
        quantidade = int(input("Digite a quantidade: "))

        
        cursor.execute("INSERT INTO pizzas_configuracao (id_tamanho, id_borda, quantidade) VALUES (?, ?, ?)",(id_pedido, item[0], item[1]))
        
        # Escolher a bebida
        cursor.execute("SELECT id_bebida, nome, descricao,preco FROM bebidas")
        bebidas = cursor.fetchall()

        print("Quer pedir bebida?")
        resposta_bebida = input("Deseja adicionar mais pizzas? (S/N)")

        if resposta.lower() != 's':
          print("Selecione uma bebida:")
          for bebida in bebidas:
              print("Código: {}".format(bebida[0]))
              print("Nome: {}".format(bebida[1]))
              print("Descrição: {}".format(bebida[2]))
              print("Preço: {}".format(bebida[3]))
              print()

          codigo_bebida = int(input("Digite o código da bebida: "))
          quantidade_bebida = int(input("Digite a quantidade: "))

          cursor.execute("SELECT id_bebida, nome, descricao,preco FROM bebidas WHERE id_bebida = ? ",(codigo_bebida))
          valor_bebida = cursor.fetchall()[3]
          valor_bebida_total = valor_bebida*quantidade_bebida
        
        # Perguntar se deseja adicionar mais pizzas
        resposta = input("Deseja fazer mais um pedido? (S/N)")
        if resposta.lower() != 's':
            break

    # Calcular valor total do pedido
    valor_pizza = float(quantidade*(valor_base + valor_borda + valor_adicional_sabor))
    valor_total = float(valor_bebida_total + valor_pizza)



    # valor_total = 0
    # for item in items_pedido:
    #     cursor.execute("SELECT preco FROM pizzas WHERE id_pizza=?", (item[0],))
    #     result = cursor.fetchone()
    #     if result is not None:
    #         valor_total += result[0] * item[1]

    # Inserir pedido na tabela de pedidos
    cursor.execute("INSERT INTO pedidos (id_cliente, id_endereco, valor_total, forma_pagamento) VALUES (?, ?, ?, ?)",
                   (id_cliente, endereco_entrega, valor_total, forma_pagamento))

    # Buscar id do pedido
    cursor.execute("SELECT last_insert_rowid()")
    id_pedido = cursor.fetchone()[0]

    # Inserir itens do pedido na tabela de itens_pedido
    for item in items_pedido:
        cursor.execute("INSERT INTO itens_pedido (id_pedido, id_pizza, quantidade) VALUES (?, ?, ?)",(id_pedido, item[0], item[1]))

    
    # Inserir pedido na tabela de histórico
    cursor.execute("INSERT INTO historico (id_pedido, data_pedido) VALUES (?, datetime('now'))", (id_pedido,))
    
    # Salvar as alterações no banco
    conn.commit()

    # Fechar a conexão com o banco de dados
    conn.close()

    print("Pedido realizado com sucesso! O valor total do pedido é R${:.2f}".format(valor_total))

In [ ]:
# solicita ao usuário a ação a ser realizada
acao = input("Digite 1 para cadastrar novo cliente ou 2 para fazer um pedido: ")

valor_pizza_especial = 10.00

if acao == "1":
    # solicita os dados do novo cliente
    nome = input("Digite o nome do cliente: ")
    telefone = input("Digite o telefone do cliente: ")

    
    rua = input("Digite a rua do endereço do cliente: ")
    numero = input("Digite o número do endereço do cliente: ")
    bairro = input("Digite o bairro do endereço do cliente: ")
    cidade = input("Digite a cidade do endereço do cliente: ")

    # insere o novo cliente
    cursor.execute("INSERT INTO clientes (nome, telefone) VALUES (?, ?)", (nome, telefone))

    # recupera o id do novo cliente
    cliente_id = cursor.lastrowid

    try:
        # insere o endereço do cliente
        cursor.execute("INSERT INTO enderecos (cliente_id, rua, numero, bairro, cidade) VALUES (?, ?, ?, ?, ?)",
                       (cliente_id, rua, numero, bairro, cidade))

        # salva as alterações no banco de dados
        conn.commit()

        print("Cliente cadastrado com sucesso!")

    except:
        print("Erro ao cadastrar novo cliente!")





elif acao == "2":
    # Exibe os sabores disponíveis
    print("Sabores disponíveis:")
    for sabor in cursor.execute("SELECT * FROM sabores"):
        print(f"{sabor[0]} - {sabor[1]} - {sabor[2]} - {sabor[3]}")

    # Pede ao usuário para selecionar um sabor
    id_sabor = int(input("Digite o ID do sabor que deseja pedir: "))

    # Exibe os tamanhos disponíveis
    print("Tamanhos disponíveis:")
    for tamanho_tal in cursor.execute("SELECT * FROM tamanhos"):
        print(f"{tamanho_tal[0]} - {tamanho_tal[1]} - {tamanho_tal[2]} - {tamanho_tal[3]}")

    # Pede ao usuário para selecionar uma bebida
    id_tamanho = input("Digite ID do tamanho: ")

    # Exibe as bebidas disponíveis
    print("Bebidas disponíveis:")
    for bebida_tal in cursor.execute("SELECT * FROM bebidas"):
        print(f"{bebida_tal[0]} - {bebida_tal[1]} - {bebida_tal[2]} - {bebida_tal[3]}")

    id_bebida = input("Digite a bebida desejada: ")

    # Verifica se o sabor escolhido está disponível
    sabor_disponivel = False
    for sabor in cursor.execute("SELECT * FROM sabores WHERE id=?", (id_sabor,)):
        sabor_disponivel = True
        descricao = sabor[2]

    if not sabor_disponivel:
        print("Sabor indisponível. Por favor, escolha outro.")

    # Obtém o endereço do cliente
    id_cliente = int(input("Digite o ID do cliente que está fazendo o pedido: "))
    id_endereco = int(input("Digite o ID do endereço: "))

    # Calculando o valor total:
    cursor.execute("SELECT preco FROM tamanhos WHERE id=?", (id_tamanho,))
    valor_final = float(cursor.fetchone()[0])
    cursor.execute("SELECT preco FROM bebidas WHERE id=?", (id_bebida,))
    valor_final = valor_final + float(cursor.fetchone()[0])
    cursor.execute("SELECT sabor_especial FROM sabores WHERE id=?", (id_sabor,))
    if cursor.fetchone()[0] == 'sim':
        valor_final = valor_final + valor_pizza_especial

    print("Valor total a pagar: ", valor_final)

    try:
        # Insere o novo pedido na tabela "pedidos"
        cursor.execute(
            "INSERT INTO pedidos (cliente_id, sabor_id, tamanho_id, bebida_id, preco_total) VALUES (?, ?, ?, ?, ?)",
            (id_cliente, id_sabor, id_tamanho, id_bebida, valor_final))
        conn.commit()
        print("Pedido cadastrado com sucesso!")

    except:
        print("Erro ao cadastrar pedido!")

else:
    print("Opção inválida. Por favor, tente novamente.")

# salva as alterações no banco de dados
conn.commit()

# fecha a conexão com o banco de dados
conn.close()